var test = require('tape')
var numbers = require('../index.js')

test('test equality of input numbers', function(t){
	t.equal(numbers(45, 'en'), '45', 'Number 45 should be equal to string 45')
	t.equal(numbers(-45, 'en'), '45', 'Number -45 should be equal to string 45')
	t.equal(numbers(4.5, 'en'), '4.5', 'Number 4.5 should be equal to string 4.5')
	t.equal(numbers(-4.5, 'en'), '4.5', 'Number -4.5 should be equal to string 4.5')
	t.equal(numbers(45, 'fa'), '۴۵', 'Number 45 should be equal to \'۴۵\' in Farsi')
	t.equal(numbers(-45, 'fa'), '۴۵', 'Number -45 should be equal to \'۴۵\' in Farsi')
	t.equal(numbers(4.5, 'fa'), '۴/۵', 'Number 4.5 should be equal to \'۴\/۵\' in Farsi')
	t.equal(numbers(-4.5, 'fa'), '۴/۵', 'Number -4.5 should be equal to \'۴\/۵\' in Farsi')
	t.equal(numbers(46, 'ar'), '٤٦', 'Number 46 should be equal to \'٤٦\' in Arabic')
	t.equal(numbers(-46, 'ar'), '٤٦', 'Number -46 should be equal to \'٤٦\' in Arabic')
	t.equal(numbers(-4.6, 'ar'), '٤/٦')
	t.equal(numbers(4.6, 'ar'), '٤/٦')
	t.equal(numbers(Infinity, 'en'), Infinity, "Infinity should be equal to Infinity for English")
	t.equal(numbers(-Infinity, 'en'), Infinity, '-Infinity should also be equal to Infinity for English')
    t.equal(numbers(Infinity, 'fa'), Infinity, 'Infinity should be equal to itself for Farsi')
    t.equal(numbers(-Infinity, 'fa'), Infinity, '-Infinity should be equal to Infinity for Farsi')
    t.equal(numbers(Infinity, 'fa'), Infinity, 'Infinity should be equal to itself for Arabic')
    t.equal(numbers(-Infinity, 'fa'), Infinity, '-Infinity should be equal to Infinity for Arabic')
	t.end()
})
